version: '3.8'
services:
  interpelbot:
    image: harbor-dev.venceremos.eu/bots/interpelbot:e90bc6c36e596fd6df5a00c86da66fd6586a947c
    container_name: interpelbot
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 100
        window: 120s
    environment:
      - TZ=Europe/Warsaw
    volumes:
      - /opt/interpelbot/data:/app/data
      - /opt/interpelbot/logs:/var/log
      - /opt/interpelbot/config.json:/app/config.json:ro
    healthcheck:
      test:
        - CMD
        - pgrep
        - crond
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
